version: '3.8'
services:
  dev-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgress
      POSTGRES_DB: db
    ports:
      - 5432:5432
